
# Targets that do not correspond to file names:
.PHONY: tests clobber

tests: 
	python run_tests.py

clobber:
	rm -f run_tests_output.txt run_tests_results.txt
	rm -f */*.o */xamr */*.data */*.pyc
	rm -rf */_output
